@ stdcall -private DllCanUnloadNow()
@ stdcall -private DllGetClassObject(ptr ptr ptr)
@ stdcall -private DllRegisterServer()
@ stdcall -private DllUnregisterServer()
@ cdecl winedmo_demuxer_check(str)
@ cdecl winedmo_demuxer_create(wstr ptr int64 ptr ptr ptr ptr)
@ cdecl winedmo_demuxer_destroy(ptr)
@ cdecl winedmo_demuxer_read(int64 ptr ptr ptr)
@ cdecl winedmo_demuxer_seek(int64 int64)
@ cdecl winedmo_demuxer_stream_lang(int64 long ptr long)
@ cdecl winedmo_demuxer_stream_name(int64 long ptr long)
@ cdecl winedmo_demuxer_stream_type(int64 long ptr ptr)
@ cdecl winedmo_muxer_add_stream(int64 long ptr ptr long)
@ cdecl winedmo_muxer_create(str ptr)
@ cdecl winedmo_muxer_destroy(int64)
@ cdecl winedmo_muxer_finalize(int64)
@ cdecl winedmo_muxer_push_sample(int64 long ptr long int64 int64 long)
@ cdecl winedmo_muxer_read_data(int64 ptr ptr ptr)
@ cdecl winedmo_muxer_start(int64)
@ cdecl -arch=win32 winedmo_transform_create(long long long long ptr ptr ptr)
@ cdecl -arch=win64 winedmo_transform_create(ptr ptr ptr ptr)
@ cdecl winedmo_transform_destroy(int64)
@ cdecl winedmo_transform_drain(int64)
@ cdecl winedmo_transform_flush(int64)
@ cdecl winedmo_transform_get_output(int64 ptr ptr ptr ptr ptr)
@ cdecl winedmo_transform_get_output_format(int64 ptr ptr)
@ cdecl winedmo_transform_push_input(int64 ptr long int64 int64 int64 long)
@ cdecl winedmo_transform_set_output_format(int64 ptr long)
@ stdcall winedmo_create_color_converter(ptr)
@ stdcall winedmo_create_wm_sync_reader(ptr ptr)
@ stdcall winedmo_create_video_decoder(ptr)
